#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# https://jamesandrewwright.com/articles/commitizen-eslint-prettier-husky/
# https://github.com/commitizen/cz-cli/issues/289#issuecomment-979245492
exec < /dev/tty && node_modules/.bin/cz --hook || true
# exec < /dev/tty && git cz --hook || true